apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # This is the name of the Argo CD application itself
  name: blog-platform-app
  # This app manifest must be created in the 'argocd' namespace
  namespace: argocd
spec:
  project: default

  # 1. WHAT to deploy (your repo)
  source:
    repoURL: https://github.com/rajnish-init/k8s-yaml-manifests.git  # <-- UPDATE THIS
    targetRevision: HEAD  # Or 'main', 'master', etc.
    path: dev/blog-platform             # <-- The folder in your repo with the manifests
    helm: 
      valueFiles:
        - values-dev.yaml

  # 2. WHERE to deploy it (your cluster)
  destination:
    server: https://kubernetes.default.svc
    # The namespace where you want your app to live
    namespace: blog-platform

  # 3. HOW to deploy it (optional, but recommended)
  syncPolicy:
    automated: # Automatically sync when the Git repo changes
      prune: true    # Delete old resources that are not in Git
      selfHeal: true # Re-sync if the live cluster state changes
    syncOptions:
    - CreateNamespace=true # Automatically create the 'blog-platform' namespace